#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if command -v npx.cmd > /dev/null 2>&1; then
    npx.cmd lint-staged
else
    npx lint-staged
fi

if command -v npm.cmd > /dev/null 2>&1; then
    npm.cmd run test
else
    npm run test
fi
