#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ "$OSTYPE" = "msys" ] || [ "$OSTYPE" = "win32" ]; then
    npx.cmd lint-staged
    npm.cmd run test
else
    npx lint-staged
    npm run test
fi
