name: Publish

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow pull request events but only for the "main" branch
  pull_request:
    branches: ['main']

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: echo HELLO
        # - run: npm ci
        # - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
